stages:
  - analysis

test:
  stage: analysis
  image: node:8
  cache:
    paths:
    - node_modules/
  before_script:
    - npm install
  script:
    - npm test

sonar-scan:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://172.16.42.19:9000/
    SONAR_PROJECT_VERSION: $CI_BUILD_ID
    SONAR_ANALYSIS_MODE: publish
  script:
    - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh
